// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djhcsmvyykevekkmjrqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqaGNzbXZ5eWtldmVra21qcnFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MDUyMTcsImV4cCI6MjA1NzM4MTIxN30.yQBZ214Kv-x_HI2Z00DhQOi-fjQJQHjB0Sagk7k_uYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);